name: youth4paws
services:
  youth4paws-homepage:
    container_name: youth4paws-homepage
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PORT: 8080
    build:
      context: website
      dockerfile: Dockerfile